name: "Fulano"
last_name: "De Tal"
job_title: "Trabajador"
phone: "666555444"
email: "fulanodetal@example.com"
website: "misitioweb.net"
avatar: "https://picsum.photos/200"
github_profile: "www.github.com/fulanodetal"
gitlab_profile: "www.gitlab.com/fulanodetal"
linkedin_profile: "www.linkedin.com/in/fulanodetal"
